---
title: "sanbdox"
author: Sylvain Schmitt
date: today
date-format: medium
format: 
  gfm:
    toc: true
    toc-depth: 1
---

This is a sandbox repository for all the small tests I wanted to create without their own repository. There are especially small codes developed for the students I'm working with.

## Usage

**sanbdox** analyses rely on the quarto documents that can be run with R and associated environment defined with [renv](#0).

## Project

**sanbdox** includes many subprojects, each with their own folder and documentation. Please explore them to understand how they work. However, the purpose of each folder is listed below.

**sanbdox** includes:

- `bien/` explore the access to the BIEN database (reference to be added).

- `bruis/` are analyses developed during the post doc of Bianca Ruis at the CRBE on modelling water table depth dynamics in TROLL.

- `dloiseau/` are analyses developed the postdoctorate of Bertille Loiseau on tree growth in relation to soil water content.

- `erivers/` are analyses developed during the post doc of Erica Rivers at the CESAB in the BioForest project.

- `gbediaga/` are analyses developed during the doctorate of Gustavo Bediaga at F&S on Brazilian forest concessions Carbon balance.

- `ialeixo/` are analyses developed during the post doc of Izabella Aleixo at INPA on modelling the effect of FACE Amazonia on forest dynamics with TROLL and analysing photosynthetic leaf efficiency with leaf age.

- `llima/` are analyses developed during the master thesis of Lucas Lima at F&S on the effect of fire and selective logging on forest height in Amazonia.

- `monitor/` are documents for the [PC Monitor](https://www.pepr-forestt.fr/projets/pc-monitor) coordination.

- `mrojat/` are analyses developed during the doctorate of Margaux Rojat at AMAP on invasive plan species in the Reunion island.

- `nrusso/` are analyses developed during the post doc of Nicholas Russo at Harvard on modelling the effect of defaunation in Central Africa on forest dynamics with TROLL.

- `prouanet/` are analyses developed during the doctorate of Paul Rouanet at AMAP on VPD microclimate modelling.

- `vbadouard/` are analyses developed during the doctorate of Vincyane Badouard at AMAP on canopy and undrestory species light niche in French Guiana.

- `z_other/` are other unclassified analyses.

Other files are:

- R environment definition with [renv](https://rstudio.github.io/renv/articles/renv.html) in `renv/` and `renv/lock`
- R files (`.Rbuildignore` , `.Rdata` , `.Rprofile` , `.Rhistory`)
- Git and GitHub files (`.gitignore` )
- Project documentation (`README.qmd` , `README.md`)

## Poeple

- Sylvain Schmitt (sylvain.schmitt\@cirad.fr)
