---
title: "Optimum diagnsotic"
author: "Schmitt"
date: last-modified
format: 
  html:
    embed-resources: true
---

```{r set}
#| message: false
#| warning: false
library(tidyverse)
set.seed(42)
```

## Background

```{r}
background <- data_frame(dbh = rlnorm(100, meanlog = 1, sdlog = 1)) %>% 
  rowwise() %>% 
  mutate(transmittance = list(rlnorm(100, meanlog = 1/10*log(dbh)-1, sdlog = 0.1))) %>% 
  unnest(transmittance)
```

```{r}
background %>% 
  gather(variable, value) %>% 
  ggplot(aes(value)) +
  geom_histogram() +
  theme_bw() +
  facet_wrap(~ variable, scales = "free_x")
```

```{r}
ggplot(background, aes(dbh, transmittance)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  theme_bw()
```

## Species

```{r}
O_1 <- 0.7
iota <- 0
inv_logit <- function(x) 1/(1+exp(-x))
data <- background %>% 
  mutate(suitability = inv_logit(-1*(log(transmittance) - (O_1 + iota*log(dbh)))^2)) %>% 
  rowwise() %>% 
  mutate(presence = list(as.numeric(rbernoulli(10, p = suitability)))) %>% 
  unnest(presence)
data %>% 
  filter(presence == 1) %>% 
  nrow()
```

## Diagnostics

```{r}
data %>% 
  filter(presence == 1) %>% 
  ggplot(aes(dbh, transmittance)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  theme_bw()
```

```{r}
data %>% 
  mutate(log_dbh_bin = cut_interval(log(dbh), n = 10),
         log_trans_bin = cut_interval(log(transmittance), n = 10)) %>% 
  group_by(presence, log_dbh_bin, log_trans_bin) %>% 
  summarise(n = n()) %>% 
  mutate(presence = recode(as.character(presence),
                           "1" = "presence", "0" = "absence")) %>% 
  pivot_wider(names_from = presence, values_from = n) %>% 
  mutate_at(vars(c("absence", "presence")), ~ ifelse(is.na(.), 0, .)) %>% 
  mutate(freq = presence/(presence+absence)) %>% 
  ungroup() %>% 
  mutate_at(vars(c("log_dbh_bin", "log_trans_bin")),
            ~gsub(c("\\[|]|\\(|)"), "", .)) %>% 
  separate(log_dbh_bin, c("log_dbh_bin_l", "log_dbh_bin_h"),
           sep = ",", convert = TRUE) %>% 
  separate(log_trans_bin, c("log_trans_bin_l", "log_trans_bin_h"),
           sep = ",", convert = TRUE) %>% 
  rowwise() %>% 
  mutate(log_dbh = mean(c(log_dbh_bin_l, log_dbh_bin_h)),
         log_trans = mean(c(log_trans_bin_l, log_trans_bin_h))) %>% 
  select(log_dbh, log_trans, freq) %>% 
  ggplot(aes(log_dbh, log_trans, fill = freq*100)) +
  geom_raster() +
  theme_bw() +
  scale_fill_viridis_c("Species\nFrequency\n[%]") +
  scale_x_continuous("Diameter at Breast Height [DBH, cm]",
                     n.breaks = 10, labels = ~round(exp(.),2)) +
  scale_y_continuous("Light Transmittance [%]",
                     n.breaks = 10, labels = ~round(exp(.)*100,2))
```

